"""
Answer generation: Cortex Analyst for member data, Cortex Search for regulation.

Citations are CONSTRUCTED here, not read off a score. Cortex Analyst returns the SQL
it generated (and a verified-query name when one matched) but no confidence value;
Cortex Search returns only the attribute columns the service declares. So the
verifiable trail an analyst reads is assembled from those parts deliberately.
"""

from __future__ import annotations

import json
import re
import sys
import time
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app import grounding, snow  # noqa: E402
from app.contracts import Answer, Citation, MemberContext, Route, SourceKind  # noqa: E402
from config import app_config as AC  # noqa: E402

ANALYST_ENDPOINT = "/api/v2/cortex/analyst/message"

# Views the generated SQL may touch. Used to report which objects backed an answer,
# which is a large part of what makes it checkable.
KNOWN_VIEWS = re.compile(r"M360MART\.SERVING\.(VW_[A-Z0-9_]+)", re.I)


def _objects_in(sql: str) -> tuple[str, ...]:
    return tuple(sorted({m.upper() for m in KNOWN_VIEWS.findall(sql or "")}))


# ---------------------------------------------------------------------------
# Cortex Analyst
# ---------------------------------------------------------------------------

def ask_analyst(question: str, ctx: MemberContext) -> tuple[str, pd.DataFrame, Citation | None, list[str]]:
    """Ask Cortex Analyst, run the SQL it returns, and build a citation.

    The member is pinned into the question rather than left to inference. Cortex
    Analyst has no notion of "the current member", and an answer about the wrong
    member is far worse than no answer.
    """
    warnings: list[str] = []
    scoped = question
    if ctx.found:
        scoped = (
            f"{question}\n\n"
            f"Scope strictly to member_id = '{ctx.member_id}'. "
            f"Report only facts present in the data. Do not recommend, predict or "
            f"rank any approval, denial or pend decision."
        )

    payload = {
        "semantic_view": AC.fqn(AC.SEMANTIC_VIEW),
        "messages": [{"role": "user", "content": [{"type": "text", "text": scoped}]}],
    }

    try:
        raw = _post_analyst(payload)
    except Exception as exc:  # noqa: BLE001
        warnings.append(f"Cortex Analyst unavailable: {str(exc).splitlines()[0][:160]}")
        return "", pd.DataFrame(), None, warnings

    sql = ""
    prose_parts: list[str] = []
    verified_name: str | None = None
    for block in raw.get("message", {}).get("content", []):
        if block.get("type") == "text":
            prose_parts.append(block.get("text", ""))
        elif block.get("type") == "sql":
            sql = block.get("statement", "")
            vq = (block.get("confidence") or {}).get("verified_query_used") or {}
            verified_name = vq.get("name")
        elif block.get("type") == "suggestion":
            # Analyst could not produce SQL and offered alternatives instead. Surface
            # them rather than pretending an answer exists.
            for s in block.get("suggestions", []) or []:
                warnings.append(f"Suggested rephrasing: {s}")

    for w in raw.get("warnings", []) or []:
        msg = w.get("message") if isinstance(w, dict) else str(w)
        if msg:
            warnings.append(str(msg)[:200])

    if not sql:
        return "\n".join(p for p in prose_parts if p).strip(), pd.DataFrame(), None, warnings

    try:
        result = snow.run_query(sql)
    except Exception as exc:  # noqa: BLE001
        warnings.append(f"Generated SQL failed to execute: {str(exc).splitlines()[0][:160]}")
        return "\n".join(prose_parts).strip(), pd.DataFrame(), None, warnings

    citation = Citation(
        kind=SourceKind.SNOWFLAKE_QUERY,
        label="Live query against the governed SERVING layer",
        detail=(f"matched verified query '{verified_name}'" if verified_name
                else "SQL generated by Cortex Analyst from the semantic view"),
        sql=sql,
        objects=_objects_in(sql) or (AC.SEMANTIC_VIEW,),
        row_count=result.row_count,
        elapsed_ms=result.elapsed_ms,
        query_id=result.query_id,
        verified_query=verified_name,
    )
    return "\n".join(prose_parts).strip(), result.df, citation, warnings


def _post_analyst(payload: dict) -> dict:
    """Call the Analyst REST endpoint, using whichever transport the mode allows."""
    if snow.in_snowflake():
        import _snowflake  # type: ignore  # available only inside SiS

        resp = _snowflake.send_snow_api_request(
            "POST", ANALYST_ENDPOINT, {}, {}, payload, None, 60_000
        )
        if resp.get("status") != 200:
            raise RuntimeError(f"Analyst HTTP {resp.get('status')}: {str(resp.get('content'))[:200]}")
        content = resp["content"]
        return json.loads(content) if isinstance(content, str) else content

    # Self-hosted: sign the REST call with the same PAT the connector uses.
    import os

    import requests

    from config import schemas as S

    cfg = S.load_config()["snowflake"]
    account = _account_host(cfg)
    token = os.environ["SNOWFLAKE_PAT"]
    resp = requests.post(
        f"https://{account}{ANALYST_ENDPOINT}",
        json=payload,
        headers={
            "Authorization": f'Bearer {token}',
            "Content-Type": "application/json",
            "X-Snowflake-Authorization-Token-Type": "PROGRAMMATIC_ACCESS_TOKEN",
        },
        timeout=120,
    )
    if resp.status_code != 200:
        raise RuntimeError(f"Analyst HTTP {resp.status_code}: {resp.text[:220]}")
    return resp.json()


def _account_host(cfg: dict) -> str:
    from load.snowflake_loader import _profile_from_toml

    account = (_profile_from_toml().get("account") or "").strip()
    if not account:
        raise RuntimeError("Could not resolve the Snowflake account identifier.")
    return f"{account.replace('_', '-')}.snowflakecomputing.com"


# ---------------------------------------------------------------------------
# Cortex Search over the regulatory corpus
# ---------------------------------------------------------------------------

def ask_regulatory(question: str, *, limit: int = 4) -> tuple[str, list[Citation], list[str]]:
    """Retrieve regulation, then have a model answer STRICTLY from what came back."""
    warnings: list[str] = []
    doc_keys = grounding.scope_documents(question)
    try:
        hits = snow.search_regulatory(question, limit=limit, doc_keys=doc_keys)
    except Exception as exc:  # noqa: BLE001
        warnings.append(f"Regulatory search unavailable: {str(exc).splitlines()[0][:160]}")
        return "", [], warnings

    if hits.empty and doc_keys:
        # The topic scope may have been too narrow; retry across the whole corpus
        # rather than reporting "no regulation found" when there is some.
        warnings.append("No match within the scoped documents; searched the full corpus.")
        try:
            hits = snow.search_regulatory(question, limit=limit)
        except Exception:  # noqa: BLE001
            hits = pd.DataFrame()

    if hits.empty:
        return "", [], warnings

    citations: list[Citation] = []
    excerpts: list[str] = []
    for i, row in hits.iterrows():
        text = str(row.get("chunk_text") or "")
        citations.append(Citation(
            kind=SourceKind.REGULATORY_DOC,
            label=str(row.get("citation_id") or "regulatory source"),
            detail=str(row.get("section_label") or ""),
            citation_id=str(row.get("citation_id") or ""),
            authority=str(row.get("authority") or ""),
            source_url=str(row.get("source_url") or ""),
            effective_date=str(row.get("effective_date") or ""),
            licence=str(row.get("licence") or ""),
            chunk_id=str(row.get("chunk_id") or ""),
            excerpt=" ".join(text[:600].split()),
        ))
        excerpts.append(f"[{i + 1}] {row.get('citation_id')} - {row.get('section_label')}\n{text[:2500]}")

    prompt = (
        "Answer the analyst's question using ONLY the numbered regulatory excerpts "
        "below. Quote the specific timeframe, threshold or requirement where one "
        "exists, and cite the bracketed number inline. If the excerpts do not "
        "contain the answer, say so plainly rather than inferring. Do not comment on "
        "whether any particular request should be approved or denied.\n\n"
        f"QUESTION: {question}\n\nEXCERPTS:\n" + "\n\n".join(excerpts)
    )
    text = snow.cortex_complete(prompt, system=AC.NON_DECISION_SYSTEM_RULE)
    if not text:
        warnings.append("The language model returned nothing; showing sources only.")
    return text.strip(), citations, warnings


# ---------------------------------------------------------------------------
# Top-level entry point
# ---------------------------------------------------------------------------

def answer(question: str, ctx: MemberContext) -> Answer:
    started = time.perf_counter()
    route = grounding.classify(question)

    if route is Route.REFUSED:
        return Answer(
            question=question, route=Route.REFUSED, text=grounding.REFUSAL_TEXT,
            elapsed_ms=int((time.perf_counter() - started) * 1000),
        )

    citations: list[Citation] = []
    warnings: list[str] = []
    parts: list[str] = []
    data: pd.DataFrame | None = None

    if route in (Route.MEMBER_DATA, Route.BOTH):
        prose, df, cite, warn = ask_analyst(question, ctx)
        warnings += warn
        if cite:
            citations.append(cite)
            data = df
            summary = _summarise_rows(question, df, ctx)
            parts.append(summary or prose)
        elif prose:
            parts.append(prose)

    if route in (Route.REGULATORY, Route.BOTH):
        prose, cites, warn = ask_regulatory(question)
        warnings += warn
        citations += cites
        if prose:
            parts.append(prose)

    text = "\n\n".join(p for p in parts if p).strip()

    if not citations:
        # In scope but nothing to cite. Say that, rather than emitting an
        # authoritative-sounding answer with no source behind it.
        return Answer(
            question=question, route=Route.UNANSWERABLE,
            text=(
                "I couldn't ground an answer to that in either the member's record or "
                "the regulatory corpus, so I'm not going to guess.\n\n"
                "Try naming the specific request, criterion or rule you're interested in."
            ),
            warnings=warnings,
            elapsed_ms=int((time.perf_counter() - started) * 1000),
        )

    blocked = grounding.check_output(text)
    return Answer(
        question=question,
        route=route,
        text=text if not blocked else "",
        citations=citations,
        data=data,
        warnings=warnings,
        blocked_reason=blocked,
        model=AC.MODEL_PRIMARY,
        elapsed_ms=int((time.perf_counter() - started) * 1000),
    )


def _summarise_rows(question: str, df: pd.DataFrame, ctx: MemberContext) -> str:
    """Have a model describe the returned rows, without adding anything to them."""
    if df is None or df.empty:
        return (
            "The query ran successfully but returned no rows, which means the "
            "record holds nothing matching that question. Absent evidence is "
            "INDETERMINATE - it is not a finding either way."
        )

    # to_string, not to_markdown: to_markdown requires `tabulate`, which is NOT
    # pre-installed in the Streamlit-in-Snowflake runtime. Depending on it would force
    # an environment.yml, and any dependency file triggers PyPI resolution that needs
    # an external access integration. to_string keeps the SiS bundle dependency-free.
    preview = df.head(40).to_string(index=False, max_colwidth=40)
    prompt = (
        "Summarise these query results for a prior-authorization analyst in at most "
        "six sentences. State only what the rows show, including counts and specific "
        "values. Where a criterion is INDETERMINATE, say that evidence is absent "
        "rather than that it failed. Never suggest or imply an approval, denial or "
        "pend decision.\n\n"
        f"QUESTION: {question}\n"
        f"MEMBER: {ctx.member_id}\n"
        f"ROWS RETURNED: {len(df)}\n\n{preview}"
    )
    return snow.cortex_complete(prompt, system=AC.NON_DECISION_SYSTEM_RULE).strip()
