"""
Iframe embedding support for the self-hosted deployment.

WHY THIS FILE EXISTS. Snowflake's own hosting cannot be iframed. Streamlit in
Snowflake, SPCS and App Runtime all sit behind a proxy that injects
`X-Frame-Options: DENY` plus `Cross-Origin-Resource-Policy: same-origin`, and the
Streamlit-in-Snowflake docs state plainly that the CSP "is not configurable at this
time". There is no flag, URL parameter or spec setting that relaxes it.

So embedding is only possible in the self-hosted mode, where we own the response
headers. This module writes the Streamlit server config that makes that work, driven
by an explicit host allow-list.

Usage:
    python app/embed.py --allow https://payer.example.com https://portal.payer.example.com
    cortex secret run --map snowflake_pat=SNOWFLAKE_PAT -- streamlit run app/main.py

Deliberately NOT offered: a wildcard allow-list. `frame-ancestors *` would let any
site frame a surface showing member health data, which invites clickjacking. If you
need many hosts, name them.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CONFIG_DIR = REPO / ".streamlit"
CONFIG_PATH = CONFIG_DIR / "config.toml"

TEMPLATE = """# Generated by app/embed.py - do not edit by hand.
#
# Streamlit's own CSRF protection blocks cross-origin framing, so embedding needs
# both of the following. They are safe ONLY because the reverse proxy in front of
# this app is expected to enforce the frame-ancestors allow-list recorded below.

[server]
# Required for the app to accept requests proxied from another origin.
enableCORS = false
# XSRF protection relies on a same-site cookie, which a cross-origin iframe cannot
# send. Disabling it is what makes framing work, and is the reason authentication
# MUST be handled by the surrounding proxy rather than by this app.
enableXsrfProtection = false
headless = true
port = {port}

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#0f2b46"

# ---------------------------------------------------------------------------
# Allowed embedding origins - enforce these at your reverse proxy:
#
#   Content-Security-Policy: frame-ancestors {frame_ancestors};
#   X-Frame-Options: <omit entirely; it cannot express an allow-list>
#
# Do NOT send X-Frame-Options alongside a frame-ancestors CSP: the older header has
# no multi-origin form, and sending both means the strictest one wins, which
# silently defeats the allow-list.
# ---------------------------------------------------------------------------
{origin_comments}
"""

NGINX_SNIPPET = """
# Reverse proxy fragment for embedding the PA copilot.
#
# The app itself cannot set frame-ancestors reliably (Streamlit serves its own
# headers), so the proxy owns it. The proxy is also where authentication belongs,
# because XSRF protection is disabled to permit framing.

location /pa-copilot/ {{
    proxy_pass         http://127.0.0.1:{port}/;
    proxy_http_version 1.1;
    proxy_set_header   Upgrade $http_upgrade;          # Streamlit needs websockets
    proxy_set_header   Connection "upgrade";
    proxy_set_header   Host $host;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto $scheme;

    # Strip whatever framing headers the upstream sent, then set our own.
    proxy_hide_header  X-Frame-Options;
    proxy_hide_header  Content-Security-Policy;
    add_header         Content-Security-Policy "frame-ancestors {frame_ancestors};" always;

    # Never cache a member-scoped surface.
    add_header         Cache-Control "no-store" always;
}}
"""


def write_config(origins: list[str], port: int) -> None:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    frame_ancestors = " ".join(origins) if origins else "'self'"
    comments = "\n".join(f"#   {o}" for o in origins) or "#   (none - standalone only)"
    CONFIG_PATH.write_text(
        TEMPLATE.format(port=port, frame_ancestors=frame_ancestors,
                        origin_comments=comments),
        encoding="utf-8",
    )
    snippet = REPO / "deploy" / "nginx-pa-copilot.conf"
    snippet.parent.mkdir(parents=True, exist_ok=True)
    snippet.write_text(
        NGINX_SNIPPET.format(port=port, frame_ancestors=frame_ancestors),
        encoding="utf-8",
    )

    print(f"wrote {CONFIG_PATH}")
    print(f"wrote {snippet}")
    print()
    print("Embed with:")
    print(f'  <iframe src="https://your-host/pa-copilot/?member_id=MBR-12345678"')
    print('          style="width:100%;height:900px;border:0"')
    print('          referrerpolicy="strict-origin"></iframe>')
    print()
    print("Reminder: XSRF protection is off so that framing works, which means the")
    print("proxy in front of this app is responsible for authenticating the analyst.")


def main() -> int:
    ap = argparse.ArgumentParser(description="Configure iframe embedding for self-hosted mode.")
    ap.add_argument("--allow", nargs="*", default=[],
                    help="explicit origins permitted to frame the app")
    ap.add_argument("--port", type=int, default=8501)
    args = ap.parse_args()

    for origin in args.allow:
        if origin.strip() in {"*", "'*'"}:
            print("Refusing a wildcard origin: it would let any site frame member "
                  "health data. Name the hosts explicitly.")
            return 1
        if not origin.startswith(("https://", "http://localhost", "http://127.0.0.1")):
            print(f"Refusing {origin!r}: use https, or localhost for development.")
            return 1

    write_config([o.strip() for o in args.allow], args.port)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
