"""
The deterministic date anchor.

PROBLEM
-------
The Synthea sample population was generated in 2020, so its most recent
encounter is years in the past. A prior-authorization datamart is useless in that
state: every SLA clock would be expired, no case would be genuinely open, and
"how many days until the regulatory deadline" would return a negative number for
every row.

SOLUTION
--------
Shift the entire timeline forward by one integer number of days, computed once
and reused by every script:

    offset = (reference_date - buffer_days) - max_source_date

Because a single offset is applied to every date in every table, all intervals
are preserved exactly - a 6-week course of physical therapy is still 6 weeks, and
an admission still precedes its discharge. Only the absolute position moves.

The offset is computed once from the source data and cached to
`.cache/date_anchor.json`. Every later script loads it rather than recomputing,
so all tables stay on one consistent timeline even when generated by separate
processes running in parallel.
"""

from __future__ import annotations

import json
from datetime import date, datetime, timedelta
from pathlib import Path

import pandas as pd

from config import schemas as S

ANCHOR_FILENAME = "date_anchor.json"


def _anchor_path() -> Path:
    cfg = S.load_config()
    cache = Path(cfg["_repo_root"]) / cfg["paths"]["cache"]
    cache.mkdir(parents=True, exist_ok=True)
    return cache / ANCHOR_FILENAME


def reference_date() -> date:
    """The 'today' the mart is built against.

    Pinned via config when a reproducible demo is wanted, otherwise the real
    current date.
    """
    cfg = S.load_config()
    pinned = cfg["date_anchor"].get("reference_date")
    if pinned:
        return date.fromisoformat(pinned)
    return datetime.now().date()


def compute_and_save(max_source_date: date, *, source_note: str = "") -> dict:
    """Compute the shift offset and cache it. Called once, by the bronze
    reference/ingest step, using the latest date found in the Synthea source."""
    cfg = S.load_config()
    buffer_days = int(cfg["date_anchor"]["recent_activity_buffer_days"])
    ref = reference_date()
    target_latest = ref - timedelta(days=buffer_days)
    offset_days = (target_latest - max_source_date).days

    anchor = {
        "offset_days": offset_days,
        "max_source_date": max_source_date.isoformat(),
        "reference_date": ref.isoformat(),
        "target_latest_date": target_latest.isoformat(),
        "recent_activity_buffer_days": buffer_days,
        "source_note": source_note,
        "computed_at": datetime.now().isoformat(timespec="seconds"),
    }
    path = _anchor_path()
    path.write_text(json.dumps(anchor, indent=2), encoding="utf-8")
    return anchor


def load() -> dict:
    path = _anchor_path()
    if not path.exists():
        raise FileNotFoundError(
            f"Date anchor not found at {path}. Run dataPrepBronze/00_fetch_open_datasets.py "
            f"first - it computes the anchor from the Synthea source data."
        )
    return json.loads(path.read_text(encoding="utf-8"))


def offset_days() -> int:
    return int(load()["offset_days"])


def shift_series(s: pd.Series) -> pd.Series:
    """Shift a date/datetime Series onto the mart timeline.

    Accepts strings, dates or datetimes and returns tz-naive datetime64. NaT
    passes through untouched so genuinely-absent dates stay absent.

    Timezone is always stripped. Synthea writes some columns with a 'Z' suffix
    (procedures.DATE, observations.DATE) and others as bare dates
    (conditions.START). Returning a mix of tz-aware and tz-naive values makes any
    concatenation of them collapse to object dtype, after which
    `to_datetime(..., errors="coerce")` silently converts the tz-aware side to
    NaT - which is how 335k clinical records lost their record_date. Every
    timestamp column in the mart is TIMESTAMP_NTZ, so naive is also the correct
    target type.
    """
    delta = pd.Timedelta(days=offset_days())
    parsed = pd.to_datetime(s, errors="coerce", utc=True)
    if isinstance(parsed.dtype, pd.DatetimeTZDtype):
        parsed = parsed.dt.tz_localize(None)
    return parsed + delta


def shift_dates(s: pd.Series) -> pd.Series:
    """Shift and return plain dates (no time component)."""
    return shift_series(s).dt.date


def shift_scalar(value: date | datetime | str | None) -> pd.Timestamp | None:
    if value is None or value == "" or pd.isna(value):
        return None
    return pd.to_datetime(value) + pd.Timedelta(days=offset_days())


def describe() -> str:
    a = load()
    return (
        f"date anchor: source latest {a['max_source_date']} -> "
        f"{a['target_latest_date']} (shift {a['offset_days']:+d} days, "
        f"reference {a['reference_date']})"
    )
