-- M360MART schema creation
-- Generated from config/schemas.py - do not edit manually.

CREATE DATABASE IF NOT EXISTS M360MART;

CREATE SCHEMA IF NOT EXISTS M360MART.BRONZE;
CREATE SCHEMA IF NOT EXISTS M360MART.SILVER;
CREATE SCHEMA IF NOT EXISTS M360MART.GOLD;
CREATE SCHEMA IF NOT EXISTS M360MART.SERVING;
