-- M360MART BRONZE layer DDL
-- Generated from config/schemas_bronze.py by sql/generate_ddl.py - do not edit manually.
-- All types are explicit (never inferred from data).

CREATE OR REPLACE TABLE M360MART.BRONZE.ref_icd10cm (
    icd10_code            VARCHAR(10) NOT NULL COMMENT 'ICD-10-CM code, no decimal point (e.g. M5416)',
    icd10_code_dotted     VARCHAR(12) NOT NULL COMMENT 'ICD-10-CM code with decimal (e.g. M54.16)',
    short_description     VARCHAR(120) COMMENT 'CMS abbreviated description',
    long_description      VARCHAR(500) COMMENT 'CMS full description',
    chapter_code          VARCHAR(10) COMMENT 'ICD-10-CM chapter range (e.g. M00-M99)',
    chapter_description   VARCHAR(200) COMMENT 'Human-readable chapter name',
    category_code         VARCHAR(5) COMMENT 'First 3 characters - the category root',
    is_billable           BOOLEAN NOT NULL COMMENT 'True when the code is valid for billing (leaf-level)',
    code_edition          VARCHAR(10) NOT NULL COMMENT 'CMS release year the code set came from',
    source_system         VARCHAR(40) NOT NULL COMMENT 'Originating system for this row (SYNTHEA, CMS_SYNPUF, FDA_NDC, CMS_ICD10, CMS_HCPCS, NPPES, SYNTHETIC, DERIVED)',
    ingested_at_utc       TIMESTAMP_NTZ NOT NULL COMMENT 'UTC timestamp the row was produced by the local pipeline',
    record_hash           VARCHAR(64) NOT NULL COMMENT 'SHA-256 over the row''s business columns. Stable across reruns with the same seed - this is what the determinism test compares.',
    CONSTRAINT pk_ref_icd10cm PRIMARY KEY (icd10_code)
)
COMMENT = 'One row per ICD-10-CM diagnosis code | Real CMS ICD-10-CM code descriptions. Source of truth for diagnosis descriptions and the crosswalk target for Synthea SNOMED conditions.';

CREATE OR REPLACE TABLE M360MART.BRONZE.ref_hcpcs (
    procedure_code          VARCHAR(10) NOT NULL COMMENT 'HCPCS/CPT procedure code',
    code_system             VARCHAR(12) NOT NULL COMMENT 'Which code system this belongs to',
    short_description       VARCHAR(120) COMMENT 'Abbreviated procedure description',
    long_description        VARCHAR(500) COMMENT 'Full procedure description',
    category                VARCHAR(60) COMMENT 'Coarse grouping (e.g. IMAGING, SURGERY, DME, DRUG)',
    pa_service_category     VARCHAR(30) COMMENT 'PA domain this code maps to, when it is a PA-relevant service',
    typically_requires_pa   BOOLEAN NOT NULL COMMENT 'True when this service is commonly subject to prior authorization',
    coverage_code           VARCHAR(4) COMMENT 'CMS coverage indicator',
    pricing_indicator       VARCHAR(4) COMMENT 'CMS pricing indicator',
    betos_code              VARCHAR(10) COMMENT 'Berenson-Eggers type of service code',
    typical_allowed_amt     NUMBER(12,2) COMMENT 'Benchmark allowed amount used to estimate cost exposure',
    code_edition            VARCHAR(16) NOT NULL COMMENT 'CMS quarterly release the code set came from',
    source_system           VARCHAR(40) NOT NULL COMMENT 'Originating system for this row (SYNTHEA, CMS_SYNPUF, FDA_NDC, CMS_ICD10, CMS_HCPCS, NPPES, SYNTHETIC, DERIVED)',
    ingested_at_utc         TIMESTAMP_NTZ NOT NULL COMMENT 'UTC timestamp the row was produced by the local pipeline',
    record_hash             VARCHAR(64) NOT NULL COMMENT 'SHA-256 over the row''s business columns. Stable across reruns with the same seed - this is what the determinism test compares.',
    CONSTRAINT pk_ref_hcpcs PRIMARY KEY (procedure_code)
)
COMMENT = 'One row per HCPCS Level II / CPT-range procedure code | Real CMS HCPCS Level II code set, plus the curated PA-relevant procedure codes used as PA request targets.';

CREATE OR REPLACE TABLE M360MART.BRONZE.ref_ndc_product (
    product_ndc                 VARCHAR(20) NOT NULL COMMENT 'FDA product NDC (labeler-product)',
    product_type                VARCHAR(60) COMMENT 'e.g. HUMAN PRESCRIPTION DRUG',
    proprietary_name            VARCHAR(400) COMMENT 'Brand name',
    nonproprietary_name         VARCHAR(600) COMMENT 'Generic name',
    dosage_form                 VARCHAR(120) COMMENT 'e.g. TABLET, INJECTION, SOLUTION',
    route                       VARCHAR(200) COMMENT 'e.g. ORAL, INTRAVENOUS, SUBCUTANEOUS',
    labeler_name                VARCHAR(300) COMMENT 'Manufacturer / labeler',
    substance_name              VARCHAR(4000) COMMENT 'Active ingredient(s)',
    active_numerator_strength   VARCHAR(500) COMMENT 'Strength value(s)',
    active_ingredient_unit      VARCHAR(1200) COMMENT 'Strength unit(s)',
    pharm_classes               VARCHAR(4000) COMMENT 'FDA pharmacologic class list',
    dea_schedule                VARCHAR(10) COMMENT 'DEA controlled-substance schedule, when applicable',
    therapeutic_class           VARCHAR(120) COMMENT 'Derived coarse therapeutic class',
    is_specialty_drug           BOOLEAN NOT NULL COMMENT 'True for high-cost specialty/biologic products that typically require PA',
    typically_requires_pa       BOOLEAN NOT NULL COMMENT 'True when the drug is commonly PA-gated',
    is_controlled_substance     BOOLEAN NOT NULL COMMENT 'True when a DEA schedule is present',
    marketing_start_date        DATE COMMENT 'FDA marketing start',
    marketing_end_date          DATE COMMENT 'FDA marketing end, when ended',
    source_system               VARCHAR(40) NOT NULL COMMENT 'Originating system for this row (SYNTHEA, CMS_SYNPUF, FDA_NDC, CMS_ICD10, CMS_HCPCS, NPPES, SYNTHETIC, DERIVED)',
    ingested_at_utc             TIMESTAMP_NTZ NOT NULL COMMENT 'UTC timestamp the row was produced by the local pipeline',
    record_hash                 VARCHAR(64) NOT NULL COMMENT 'SHA-256 over the row''s business columns. Stable across reruns with the same seed - this is what the determinism test compares.',
    CONSTRAINT pk_ref_ndc_product PRIMARY KEY (product_ndc)
)
COMMENT = 'One row per NDC product code | Real FDA National Drug Code directory. Supplies drug identity, therapeutic class and specialty/PA flags for pharmacy PA requests.';

CREATE OR REPLACE TABLE M360MART.BRONZE.ref_provider_npi (
    npi                     VARCHAR(10) NOT NULL COMMENT '10-digit National Provider Identifier',
    entity_type             VARCHAR(2) NOT NULL COMMENT '1 = individual practitioner, 2 = organization',
    provider_name           VARCHAR(300) NOT NULL COMMENT 'Display name (person or organization)',
    first_name              VARCHAR(100) COMMENT 'Given name, individuals only',
    last_name               VARCHAR(100) COMMENT 'Family name, individuals only',
    credential              VARCHAR(60) COMMENT 'e.g. MD, DO, NP, PA-C',
    gender                  VARCHAR(2) COMMENT 'Provider gender, individuals only',
    primary_taxonomy_code   VARCHAR(20) COMMENT 'NUCC taxonomy code',
    primary_specialty       VARCHAR(150) COMMENT 'Specialty description',
    organization_name       VARCHAR(300) COMMENT 'Affiliated organization',
    practice_city           VARCHAR(100) COMMENT 'Practice location city',
    practice_state          VARCHAR(2) COMMENT 'Practice location state',
    practice_zip            VARCHAR(10) COMMENT 'Practice location ZIP',
    practice_phone          VARCHAR(30) COMMENT 'Practice phone',
    enumeration_date        DATE COMMENT 'Date the NPI was issued',
    is_sole_proprietor      BOOLEAN COMMENT 'NPPES sole-proprietor flag',
    is_synthetic_npi        BOOLEAN NOT NULL COMMENT 'True when the NPI was generated rather than sourced from NPPES',
    source_system           VARCHAR(40) NOT NULL COMMENT 'Originating system for this row (SYNTHEA, CMS_SYNPUF, FDA_NDC, CMS_ICD10, CMS_HCPCS, NPPES, SYNTHETIC, DERIVED)',
    ingested_at_utc         TIMESTAMP_NTZ NOT NULL COMMENT 'UTC timestamp the row was produced by the local pipeline',
    record_hash             VARCHAR(64) NOT NULL COMMENT 'SHA-256 over the row''s business columns. Stable across reruns with the same seed - this is what the determinism test compares.',
    CONSTRAINT pk_ref_provider_npi PRIMARY KEY (npi)
)
COMMENT = 'One row per provider NPI (individual or organization) | Provider reference. Real NPPES records where the API returned them, otherwise deterministic Luhn-valid synthetic NPIs. The is_synthetic_npi flag makes the distinction explicit and auditable.';

CREATE OR REPLACE TABLE M360MART.BRONZE.ref_place_of_service (
    pos_code          VARCHAR(4) NOT NULL COMMENT 'Two-digit place-of-service code',
    pos_name          VARCHAR(120) NOT NULL COMMENT 'Short name (e.g. Office, Inpatient Hospital)',
    pos_description   VARCHAR(600) COMMENT 'Full CMS description',
    facility_type     VARCHAR(30) COMMENT 'FACILITY or NON_FACILITY',
    is_inpatient      BOOLEAN NOT NULL COMMENT 'True for inpatient settings',
    source_system     VARCHAR(40) NOT NULL COMMENT 'Originating system for this row (SYNTHEA, CMS_SYNPUF, FDA_NDC, CMS_ICD10, CMS_HCPCS, NPPES, SYNTHETIC, DERIVED)',
    ingested_at_utc   TIMESTAMP_NTZ NOT NULL COMMENT 'UTC timestamp the row was produced by the local pipeline',
    record_hash       VARCHAR(64) NOT NULL COMMENT 'SHA-256 over the row''s business columns. Stable across reruns with the same seed - this is what the determinism test compares.',
    CONSTRAINT pk_ref_place_of_service PRIMARY KEY (pos_code)
)
COMMENT = 'One row per CMS place-of-service code | CMS place-of-service code set. Needed for site-of-service criteria.';

CREATE OR REPLACE TABLE M360MART.BRONZE.ref_synpuf_benchmark (
    benchmark_id        VARCHAR(60) NOT NULL COMMENT 'Cohort + metric identifier',
    cohort              VARCHAR(60) NOT NULL COMMENT 'Benchmark cohort (e.g. ALL, AGE_65_74, ESRD)',
    metric_name         VARCHAR(80) NOT NULL COMMENT 'Metric being described (e.g. inpatient_beneficiary_responsibility)',
    p10                 NUMBER(14,2) COMMENT '10th percentile',
    p25                 NUMBER(14,2) COMMENT '25th percentile',
    p50                 NUMBER(14,2) COMMENT 'Median',
    p75                 NUMBER(14,2) COMMENT '75th percentile',
    p90                 NUMBER(14,2) COMMENT '90th percentile',
    mean_value          NUMBER(14,2) COMMENT 'Arithmetic mean',
    stddev_value        NUMBER(14,2) COMMENT 'Standard deviation',
    observation_count   NUMBER(12,0) COMMENT 'Beneficiaries contributing to the metric',
    source_year         VARCHAR(10) COMMENT 'SynPUF data year',
    source_system       VARCHAR(40) NOT NULL COMMENT 'Originating system for this row (SYNTHEA, CMS_SYNPUF, FDA_NDC, CMS_ICD10, CMS_HCPCS, NPPES, SYNTHETIC, DERIVED)',
    ingested_at_utc     TIMESTAMP_NTZ NOT NULL COMMENT 'UTC timestamp the row was produced by the local pipeline',
    record_hash         VARCHAR(64) NOT NULL COMMENT 'SHA-256 over the row''s business columns. Stable across reruns with the same seed - this is what the determinism test compares.',
    CONSTRAINT pk_ref_synpuf_benchmark PRIMARY KEY (benchmark_id)
)
COMMENT = 'One row per cost-sharing metric per benchmark cohort | CALIBRATION ONLY. Percentile distributions derived from the CMS DE-SynPUF beneficiary summary, used to shape synthetic accumulators so member financial values follow a realistic real-world spread rather than an invented one. Never a row source for member data.';

CREATE OR REPLACE TABLE M360MART.BRONZE.dim_memberProfile (
    member_id                          VARCHAR(20) NOT NULL COMMENT 'Payer-assigned member identifier (MBR-########). Generated by common.identity, which guarantees uniqueness - a truncated hash alone collides at this population size and Snowflake does not enforce the PK.',
    synthea_patient_id                 VARCHAR(64) COMMENT 'Originating Synthea patient UUID. Lineage only - never exposed in SERVING.',
    subscriber_id                      VARCHAR(20) COMMENT 'Subscriber this member belongs to',
    relationship_to_subscriber         VARCHAR(20) COMMENT 'SELF, SPOUSE, CHILD, OTHER',
    mbi                                VARCHAR(20) COMMENT 'Medicare Beneficiary Identifier, when Medicare Advantage',
    ssn_last4                          VARCHAR(4) COMMENT 'Last 4 of SSN. Excluded from SERVING views.',
    first_name                         VARCHAR(100) NOT NULL COMMENT 'Given name',
    middle_name                        VARCHAR(100) COMMENT 'Middle name',
    last_name                          VARCHAR(100) NOT NULL COMMENT 'Family name',
    name_suffix                        VARCHAR(20) COMMENT 'Generational suffix',
    date_of_birth                      DATE NOT NULL COMMENT 'Date of birth (date-anchor shifted)',
    age_years                          NUMBER(5,0) NOT NULL COMMENT 'Age in whole years as of the pipeline reference date',
    date_of_death                      DATE COMMENT 'Date of death when deceased',
    deceased_flag                      BOOLEAN NOT NULL COMMENT 'True when a date of death is present',
    gender                             VARCHAR(2) NOT NULL COMMENT 'Administrative gender',
    race                               VARCHAR(60) COMMENT 'Race as recorded in the source',
    ethnicity                          VARCHAR(60) COMMENT 'Ethnicity as recorded in the source',
    marital_status                     VARCHAR(20) COMMENT 'Marital status',
    preferred_language                 VARCHAR(40) COMMENT 'Preferred spoken language - drives correspondence requirements',
    interpreter_needed_flag            BOOLEAN NOT NULL COMMENT 'True when language is not English',
    address_line1                      VARCHAR(200) COMMENT 'Street address. Excluded from SERVING views.',
    city                               VARCHAR(100) COMMENT 'City',
    county                             VARCHAR(100) COMMENT 'County',
    state                              VARCHAR(2) COMMENT 'State - drives state-specific PA turnaround rules',
    zip_code                           VARCHAR(10) COMMENT 'Postal code',
    latitude                           NUMBER(11,7) COMMENT 'Latitude. Excluded from SERVING views.',
    longitude                          NUMBER(11,7) COMMENT 'Longitude. Excluded from SERVING views.',
    phone                              VARCHAR(30) COMMENT 'Contact phone. Excluded from SERVING views.',
    email                              VARCHAR(200) COMMENT 'Contact email. Excluded from SERVING views.',
    annual_income_amt                  NUMBER(12,2) COMMENT 'Reported annual income',
    healthcare_expenses_lifetime_amt   NUMBER(14,2) COMMENT 'Lifetime healthcare expenses from source',
    healthcare_coverage_lifetime_amt   NUMBER(14,2) COMMENT 'Lifetime covered amount from source',
    is_current                         BOOLEAN NOT NULL COMMENT 'True for the active profile record',
    source_system                      VARCHAR(40) NOT NULL COMMENT 'Originating system for this row (SYNTHEA, CMS_SYNPUF, FDA_NDC, CMS_ICD10, CMS_HCPCS, NPPES, SYNTHETIC, DERIVED)',
    ingested_at_utc                    TIMESTAMP_NTZ NOT NULL COMMENT 'UTC timestamp the row was produced by the local pipeline',
    record_hash                        VARCHAR(64) NOT NULL COMMENT 'SHA-256 over the row''s business columns. Stable across reruns with the same seed - this is what the determinism test compares.',
    CONSTRAINT pk_dim_memberprofile PRIMARY KEY (member_id)
)
COMMENT = 'One row per member (the payer''s own view of the person) | Member demographic master, derived from Synthea patients.csv with all dates shifted by the deterministic date anchor. This is the payer-side identity; ext_patientProfile is the provider-side identity for the same human and the two are reconciled in silver.';

CREATE OR REPLACE TABLE M360MART.BRONZE.dim_memberPlan (
    member_plan_sk                    VARCHAR(40) NOT NULL COMMENT 'Surrogate key for the member-plan span',
    member_id                         VARCHAR(20) NOT NULL COMMENT 'Member this coverage belongs to',
    plan_id                           VARCHAR(30) NOT NULL COMMENT 'Plan identifier',
    plan_name                         VARCHAR(200) NOT NULL COMMENT 'Marketing plan name',
    payer_id                          VARCHAR(30) NOT NULL COMMENT 'Payer identifier',
    payer_name                        VARCHAR(200) NOT NULL COMMENT 'Payer name',
    line_of_business                  VARCHAR(30) NOT NULL COMMENT 'Regulatory line of business - selects the applicable TAT rule',
    product_type                      VARCHAR(10) NOT NULL COMMENT 'Network product design',
    metal_tier                        VARCHAR(20) COMMENT 'Marketplace actuarial tier, when applicable',
    group_number                      VARCHAR(30) COMMENT 'Employer group number',
    group_name                        VARCHAR(200) COMMENT 'Employer group name',
    coverage_start_date               DATE NOT NULL COMMENT 'First day of coverage',
    coverage_end_date                 DATE COMMENT 'Last day of coverage, NULL when open-ended',
    is_current                        BOOLEAN NOT NULL COMMENT 'True for the span covering the reference date',
    enrollment_status                 VARCHAR(20) NOT NULL COMMENT 'Coverage state',
    pcp_npi                           VARCHAR(10) COMMENT 'Assigned primary care provider NPI',
    pcp_name                          VARCHAR(300) COMMENT 'Assigned primary care provider name',
    pharmacy_carveout_flag            BOOLEAN NOT NULL COMMENT 'True when pharmacy benefits are administered by a separate PBM',
    pharmacy_pbm_name                 VARCHAR(120) COMMENT 'PBM name when carved out',
    behavioral_health_carveout_flag   BOOLEAN NOT NULL COMMENT 'True when behavioral health is carved out to a vendor',
    behavioral_health_vendor_name     VARCHAR(120) COMMENT 'BH vendor when carved out',
    state_of_issue                    VARCHAR(2) NOT NULL COMMENT 'State the plan was issued in',
    regulatory_tat_standard_days      NUMBER(5,0) NOT NULL COMMENT 'Calendar days allowed for a standard PA decision under this LOB',
    regulatory_tat_urgent_hours       NUMBER(5,0) NOT NULL COMMENT 'Hours allowed for an expedited PA decision under this LOB',
    tat_authority                     VARCHAR(200) NOT NULL COMMENT 'Regulation the turnaround limits come from',
    pa_ruleset_id                     VARCHAR(30) NOT NULL COMMENT 'Identifier of the PA-required service list this plan uses',
    source_system                     VARCHAR(40) NOT NULL COMMENT 'Originating system for this row (SYNTHEA, CMS_SYNPUF, FDA_NDC, CMS_ICD10, CMS_HCPCS, NPPES, SYNTHETIC, DERIVED)',
    ingested_at_utc                   TIMESTAMP_NTZ NOT NULL COMMENT 'UTC timestamp the row was produced by the local pipeline',
    record_hash                       VARCHAR(64) NOT NULL COMMENT 'SHA-256 over the row''s business columns. Stable across reruns with the same seed - this is what the determinism test compares.',
    CONSTRAINT pk_dim_memberplan PRIMARY KEY (member_plan_sk)
)
COMMENT = 'One row per member per plan coverage span | Plan enrolment and benefit configuration. Carries the line of business, carve-outs and the regulatory turnaround pair that every downstream SLA calculation depends on.';

CREATE OR REPLACE TABLE M360MART.BRONZE.dim_memberFinance (
    member_finance_sk              VARCHAR(40) NOT NULL COMMENT 'Surrogate key',
    member_id                      VARCHAR(20) NOT NULL COMMENT 'Member',
    plan_id                        VARCHAR(30) NOT NULL COMMENT 'Plan',
    benefit_year                   NUMBER(4,0) NOT NULL COMMENT 'Benefit year',
    deductible_individual_amt      NUMBER(12,2) NOT NULL COMMENT 'Annual individual deductible',
    deductible_met_amt             NUMBER(12,2) NOT NULL COMMENT 'Deductible satisfied year to date',
    deductible_remaining_amt       NUMBER(12,2) NOT NULL COMMENT 'Deductible still owed',
    deductible_met_flag            BOOLEAN NOT NULL COMMENT 'True when the deductible is fully satisfied',
    oop_max_individual_amt         NUMBER(12,2) NOT NULL COMMENT 'Annual individual out-of-pocket maximum',
    oop_met_amt                    NUMBER(12,2) NOT NULL COMMENT 'Out-of-pocket satisfied year to date',
    oop_remaining_amt              NUMBER(12,2) NOT NULL COMMENT 'Remaining exposure before the OOP max',
    oop_max_met_flag               BOOLEAN NOT NULL COMMENT 'True when the OOP maximum is reached',
    coinsurance_pct                NUMBER(5,2) NOT NULL COMMENT 'Member coinsurance percentage',
    pcp_copay_amt                  NUMBER(10,2) COMMENT 'Primary care visit copay',
    specialist_copay_amt           NUMBER(10,2) COMMENT 'Specialist visit copay',
    er_copay_amt                   NUMBER(10,2) COMMENT 'Emergency room copay',
    urgent_care_copay_amt          NUMBER(10,2) COMMENT 'Urgent care copay',
    inpatient_copay_per_day_amt    NUMBER(10,2) COMMENT 'Inpatient per-diem copay',
    inpatient_copay_max_days       NUMBER(5,0) COMMENT 'Days the per-diem copay applies for',
    rx_deductible_amt              NUMBER(10,2) COMMENT 'Separate pharmacy deductible',
    rx_tier1_copay_amt             NUMBER(10,2) COMMENT 'Generic tier copay',
    rx_tier2_copay_amt             NUMBER(10,2) COMMENT 'Preferred brand tier copay',
    rx_tier3_copay_amt             NUMBER(10,2) COMMENT 'Non-preferred brand tier copay',
    rx_specialty_coinsurance_pct   NUMBER(5,2) COMMENT 'Specialty drug coinsurance percentage',
    premium_monthly_amt            NUMBER(10,2) COMMENT 'Monthly premium',
    premium_paid_through_date      DATE COMMENT 'Premium paid through',
    premium_delinquent_flag        BOOLEAN NOT NULL COMMENT 'True when premium is unpaid - relevant to eligibility questions',
    grace_period_end_date          DATE COMMENT 'End of premium grace period when delinquent',
    hsa_fsa_balance_amt            NUMBER(12,2) COMMENT 'HSA/FSA balance available',
    ytd_allowed_amt                NUMBER(14,2) NOT NULL COMMENT 'Year-to-date allowed amount',
    ytd_plan_paid_amt              NUMBER(14,2) NOT NULL COMMENT 'Year-to-date plan paid',
    ytd_member_paid_amt            NUMBER(14,2) NOT NULL COMMENT 'Year-to-date member paid',
    is_current                     BOOLEAN NOT NULL COMMENT 'True for the current benefit year',
    source_system                  VARCHAR(40) NOT NULL COMMENT 'Originating system for this row (SYNTHEA, CMS_SYNPUF, FDA_NDC, CMS_ICD10, CMS_HCPCS, NPPES, SYNTHETIC, DERIVED)',
    ingested_at_utc                TIMESTAMP_NTZ NOT NULL COMMENT 'UTC timestamp the row was produced by the local pipeline',
    record_hash                    VARCHAR(64) NOT NULL COMMENT 'SHA-256 over the row''s business columns. Stable across reruns with the same seed - this is what the determinism test compares.',
    CONSTRAINT pk_dim_memberfinance PRIMARY KEY (member_finance_sk)
)
COMMENT = 'One row per member per plan per benefit year | Cost-sharing design and accumulator position. Percentile shapes are calibrated against ref_synpuf_benchmark so member financial exposure follows a realistic distribution.';

CREATE OR REPLACE TABLE M360MART.BRONZE.dim_memberHistory (
    member_history_sk           VARCHAR(40) NOT NULL COMMENT 'Surrogate key',
    member_id                   VARCHAR(20) NOT NULL COMMENT 'Member',
    sequence_number             NUMBER(6,0) NOT NULL COMMENT 'Ordering of events within a member',
    change_type                 VARCHAR(30) NOT NULL COMMENT 'Nature of the change',
    effective_start_date        DATE NOT NULL COMMENT 'Date the change takes effect',
    effective_end_date          DATE COMMENT 'Date the state ended, NULL when still in force',
    processed_date              DATE NOT NULL COMMENT 'Date the change was actually processed - later than effective_start_date on retro actions',
    enrollment_status           VARCHAR(20) NOT NULL COMMENT 'Resulting status',
    changed_attribute           VARCHAR(60) COMMENT 'Attribute that changed',
    prior_value                 VARCHAR(200) COMMENT 'Value before the change',
    new_value                   VARCHAR(200) COMMENT 'Value after the change',
    change_reason_code          VARCHAR(20) COMMENT 'Reason code',
    change_reason_desc          VARCHAR(200) COMMENT 'Reason description',
    plan_id                     VARCHAR(30) COMMENT 'Plan in force after the change',
    retroactive_flag            BOOLEAN NOT NULL COMMENT 'True when processed_date is after effective_start_date',
    retroactive_days            NUMBER(6,0) COMMENT 'How far back the change was applied',
    coverage_gap_days           NUMBER(6,0) COMMENT 'Days of no coverage created immediately before this event',
    creates_coverage_gap_flag   BOOLEAN NOT NULL COMMENT 'True when this event opened a gap',
    source_system               VARCHAR(40) NOT NULL COMMENT 'Originating system for this row (SYNTHEA, CMS_SYNPUF, FDA_NDC, CMS_ICD10, CMS_HCPCS, NPPES, SYNTHETIC, DERIVED)',
    ingested_at_utc             TIMESTAMP_NTZ NOT NULL COMMENT 'UTC timestamp the row was produced by the local pipeline',
    record_hash                 VARCHAR(64) NOT NULL COMMENT 'SHA-256 over the row''s business columns. Stable across reruns with the same seed - this is what the determinism test compares.',
    CONSTRAINT pk_dim_memberhistory PRIMARY KEY (member_history_sk)
)
COMMENT = 'One row per member per enrolment/status change event | Append-only change log for member status. Includes coverage gaps and retroactive terminations, which are a common root cause of PA eligibility denials and therefore something an analyst must be able to see directly.';

CREATE OR REPLACE TABLE M360MART.BRONZE.fct_memberPA (
    pa_id                               VARCHAR(24) NOT NULL COMMENT 'Prior authorization case identifier (PA-YYYY-######)',
    member_id                           VARCHAR(20) NOT NULL COMMENT 'Member the request is for',
    plan_id                             VARCHAR(30) NOT NULL COMMENT 'Plan in force at submission',
    line_of_business                    VARCHAR(30) NOT NULL COMMENT 'LOB at submission - determines which TAT rule applies',
    submitted_datetime_utc              TIMESTAMP_NTZ NOT NULL COMMENT 'When the provider submitted',
    received_datetime_utc               TIMESTAMP_NTZ NOT NULL COMMENT 'When the payer logged receipt - this starts the regulatory clock',
    request_channel                     VARCHAR(20) NOT NULL COMMENT 'How the request arrived',
    certification_type                  VARCHAR(20) NOT NULL COMMENT 'Initial, extension, renewal or appeal',
    urgency_flag                        VARCHAR(20) NOT NULL COMMENT 'Requested review speed',
    urgency_clinically_justified_flag   BOOLEAN COMMENT 'Whether the clinical picture supports the requested urgency. NULL when not assessed.',
    service_category                    VARCHAR(30) NOT NULL COMMENT 'PA domain',
    requested_procedure_code            VARCHAR(10) COMMENT 'Requested CPT/HCPCS/ICD-10-PCS code',
    requested_code_system               VARCHAR(12) COMMENT 'Code system of the requested procedure',
    requested_procedure_desc            VARCHAR(500) COMMENT 'Requested procedure description',
    requested_ndc                       VARCHAR(20) COMMENT 'Requested drug NDC, for pharmacy PA',
    requested_drug_name                 VARCHAR(300) COMMENT 'Requested drug name, for pharmacy PA',
    primary_dx_icd10                    VARCHAR(10) NOT NULL COMMENT 'Primary supporting diagnosis',
    primary_dx_desc                     VARCHAR(500) COMMENT 'Primary diagnosis description',
    secondary_dx_icd10_list             VARIANT COMMENT 'Array of additional supporting diagnoses',
    place_of_service_code               VARCHAR(4) COMMENT 'Requested place of service',
    place_of_service_desc               VARCHAR(120) COMMENT 'Place of service description',
    requested_units                     NUMBER(10,0) COMMENT 'Units, visits or days requested',
    requested_start_date                DATE COMMENT 'Requested service start',
    requested_end_date                  DATE COMMENT 'Requested service end',
    ordering_provider_npi               VARCHAR(10) COMMENT 'Ordering provider NPI',
    ordering_provider_name              VARCHAR(300) COMMENT 'Ordering provider name',
    ordering_provider_specialty         VARCHAR(150) COMMENT 'Ordering provider specialty',
    rendering_provider_npi              VARCHAR(10) COMMENT 'Rendering provider NPI',
    rendering_facility_npi              VARCHAR(10) COMMENT 'Rendering facility NPI',
    rendering_facility_name             VARCHAR(300) COMMENT 'Rendering facility name',
    network_status_at_submission        VARCHAR(20) NOT NULL COMMENT 'Network standing of the requesting provider at submission',
    single_case_agreement_flag          BOOLEAN NOT NULL COMMENT 'True when an out-of-network provider has an SCA or gap exception',
    estimated_allowed_amt               NUMBER(12,2) COMMENT 'Benchmark allowed amount for the requested service',
    high_cost_review_flag               BOOLEAN NOT NULL COMMENT 'True when the estimated amount crosses the additional-review threshold',
    criteria_ruleset_id                 VARCHAR(40) COMMENT 'Ruleset used to review this request - joins to slv_pa_criteria_ruleset',
    criteria_ruleset_version            VARCHAR(20) COMMENT 'Ruleset version applied',
    pa_status                           VARCHAR(24) NOT NULL COMMENT 'Current case status',
    is_open_flag                        BOOLEAN NOT NULL COMMENT 'True when the case is still open and its SLA clock is running',
    decision_datetime_utc               TIMESTAMP_NTZ COMMENT 'When a final decision was rendered',
    decision_by_role                    VARCHAR(24) COMMENT 'Who decided',
    decision_by_user_id                 VARCHAR(40) COMMENT 'Reviewer identifier',
    denial_reason_code                  VARCHAR(10) COMMENT 'Denial reason',
    denial_reason_desc                  VARCHAR(300) COMMENT 'Specific denial reason - CMS-0057-F requires specificity, not ''does not meet criteria''',
    approved_units                      NUMBER(10,0) COMMENT 'Units approved - less than requested on a partial approval',
    auth_number                         VARCHAR(30) COMMENT 'Authorization number issued on approval. Joins to fct_memberTransactions.related_auth_number.',
    auth_effective_date                 DATE COMMENT 'Authorization valid from',
    auth_expiration_date                DATE COMMENT 'Authorization valid until',
    pend_reason_code                    VARCHAR(10) COMMENT 'Why the case was pended',
    pend_reason_desc                    VARCHAR(300) COMMENT 'Pend reason description',
    pend_letter_sent_date               DATE COMMENT 'Date the request-for-information went out',
    pend_response_received_date         DATE COMMENT 'Date the provider responded',
    clock_paused_days                   NUMBER(6,0) NOT NULL COMMENT 'Days excluded from the regulatory clock while pended',
    auto_adjudicated_flag               BOOLEAN NOT NULL COMMENT 'True when decided without human review',
    auto_adjudication_reason            VARCHAR(200) COMMENT 'Why the rules engine auto-decided, or why it routed to manual review',
    gold_card_exempt_flag               BOOLEAN NOT NULL COMMENT 'True when the provider was PA-exempt for this service at submission',
    regulatory_deadline_datetime_utc    TIMESTAMP_NTZ NOT NULL COMMENT 'Hard decision deadline, computed from LOB, urgency and receipt time',
    tat_elapsed_days                    NUMBER(8,2) COMMENT 'Days elapsed against the clock, excluding pend pauses',
    sla_breach_flag                     BOOLEAN NOT NULL COMMENT 'True when the deadline has already passed',
    letter_of_medical_necessity_flag    BOOLEAN NOT NULL COMMENT 'True when an LMN was submitted',
    attachment_count                    NUMBER(5,0) NOT NULL COMMENT 'Number of clinical attachments',
    clinical_notes_attached_flag        BOOLEAN NOT NULL COMMENT 'True when progress notes were submitted',
    lab_results_attached_flag           BOOLEAN NOT NULL COMMENT 'True when lab results were submitted',
    imaging_attached_flag               BOOLEAN NOT NULL COMMENT 'True when imaging results were submitted',
    appeal_flag                         BOOLEAN NOT NULL COMMENT 'True when the decision was appealed',
    appeal_filed_date                   DATE COMMENT 'Date the appeal was filed',
    appeal_outcome                      VARCHAR(30) COMMENT 'UPHELD, OVERTURNED, PARTIALLY_OVERTURNED or WITHDRAWN',
    appeal_decision_date                DATE COMMENT 'Date the appeal was decided',
    grounded_on_source                  VARCHAR(40) COMMENT 'Which real source record seeded this request (CONDITION, ENCOUNTER, MEDICATION, PROCEDURE)',
    grounded_on_source_id               VARCHAR(80) COMMENT 'Identifier of the seeding source record - makes the grounding auditable',
    source_system                       VARCHAR(40) NOT NULL COMMENT 'Originating system for this row (SYNTHEA, CMS_SYNPUF, FDA_NDC, CMS_ICD10, CMS_HCPCS, NPPES, SYNTHETIC, DERIVED)',
    ingested_at_utc                     TIMESTAMP_NTZ NOT NULL COMMENT 'UTC timestamp the row was produced by the local pipeline',
    record_hash                         VARCHAR(64) NOT NULL COMMENT 'SHA-256 over the row''s business columns. Stable across reruns with the same seed - this is what the determinism test compares.',
    CONSTRAINT pk_fct_memberpa PRIMARY KEY (pa_id)
)
COMMENT = 'One row per prior authorization request | The centrepiece fact. No public dataset contains real PA records, so these are synthesised - but every request is GROUNDED in an actual Synthea condition, encounter or medication for the same member. That grounding is what makes the clinical evidence in ext_* genuinely corroborate or contradict the request, rather than being decorative. A deliberate slice of cases is left open with live SLA clocks.';

CREATE OR REPLACE TABLE M360MART.BRONZE.fct_memberTransactions (
    transaction_id              VARCHAR(40) NOT NULL COMMENT 'Unique transaction identifier',
    claim_id                    VARCHAR(40) COMMENT 'Claim this line belongs to',
    claim_line_number           NUMBER(6,0) COMMENT 'Line number within the claim',
    member_id                   VARCHAR(20) NOT NULL COMMENT 'Member',
    plan_id                     VARCHAR(30) COMMENT 'Plan in force on the service date',
    transaction_type            VARCHAR(30) NOT NULL COMMENT 'Kind of transaction',
    claim_status                VARCHAR(20) COMMENT 'Adjudication outcome',
    service_start_date          DATE COMMENT 'First date of service',
    service_end_date            DATE COMMENT 'Last date of service',
    received_date               DATE COMMENT 'Date the claim was received',
    adjudicated_date            DATE COMMENT 'Date the claim was adjudicated',
    paid_date                   DATE COMMENT 'Date payment was issued',
    billing_provider_npi        VARCHAR(10) COMMENT 'Billing provider NPI',
    rendering_provider_npi      VARCHAR(10) COMMENT 'Rendering provider NPI',
    facility_npi                VARCHAR(10) COMMENT 'Facility NPI',
    provider_network_status     VARCHAR(20) COMMENT 'Network standing',
    place_of_service_code       VARCHAR(4) COMMENT 'Place of service',
    procedure_code              VARCHAR(10) COMMENT 'Procedure code billed',
    procedure_code_system       VARCHAR(12) COMMENT 'Procedure code system',
    procedure_desc              VARCHAR(500) COMMENT 'Procedure description',
    modifier_1                  VARCHAR(4) COMMENT 'First procedure modifier',
    modifier_2                  VARCHAR(4) COMMENT 'Second procedure modifier',
    revenue_code                VARCHAR(6) COMMENT 'Institutional revenue code',
    drg_code                    VARCHAR(10) COMMENT 'Diagnosis-related group, inpatient only',
    units_of_service            NUMBER(10,2) COMMENT 'Units billed',
    primary_dx_icd10            VARCHAR(10) COMMENT 'Primary diagnosis on the line',
    dx_icd10_list               VARIANT COMMENT 'Array of all diagnoses on the claim',
    ndc_code                    VARCHAR(20) COMMENT 'Drug NDC, pharmacy claims only',
    drug_name                   VARCHAR(300) COMMENT 'Drug name, pharmacy claims only',
    quantity_dispensed          NUMBER(12,3) COMMENT 'Quantity dispensed',
    days_supply                 NUMBER(6,0) COMMENT 'Days supply dispensed',
    fill_number                 NUMBER(4,0) COMMENT 'Refill sequence, 0 = original fill',
    is_generic                  BOOLEAN COMMENT 'True for generic dispense',
    formulary_tier              NUMBER(2,0) COMMENT 'Formulary tier at time of fill',
    billed_amt                  NUMBER(14,2) COMMENT 'Provider billed charge',
    allowed_amt                 NUMBER(14,2) COMMENT 'Contractually allowed amount',
    plan_paid_amt               NUMBER(14,2) COMMENT 'Amount the plan paid',
    member_deductible_amt       NUMBER(14,2) COMMENT 'Applied to deductible',
    member_coinsurance_amt      NUMBER(14,2) COMMENT 'Member coinsurance',
    member_copay_amt            NUMBER(14,2) COMMENT 'Member copay',
    member_responsibility_amt   NUMBER(14,2) COMMENT 'Total member responsibility on the line',
    cob_paid_amt                NUMBER(14,2) COMMENT 'Paid by another carrier under COB',
    adjustment_amt              NUMBER(14,2) COMMENT 'Adjustment applied - may be negative',
    outstanding_amt             NUMBER(14,2) COMMENT 'Balance still outstanding',
    related_auth_number         VARCHAR(30) COMMENT 'Authorization that permitted this service, when one existed',
    pa_required_flag            BOOLEAN COMMENT 'True when the service required PA',
    pa_on_file_flag             BOOLEAN COMMENT 'True when a matching authorization was found',
    denial_code                 VARCHAR(20) COMMENT 'Claim denial code',
    denial_desc                 VARCHAR(300) COMMENT 'Claim denial description',
    source_system               VARCHAR(40) NOT NULL COMMENT 'Originating system for this row (SYNTHEA, CMS_SYNPUF, FDA_NDC, CMS_ICD10, CMS_HCPCS, NPPES, SYNTHETIC, DERIVED)',
    ingested_at_utc             TIMESTAMP_NTZ NOT NULL COMMENT 'UTC timestamp the row was produced by the local pipeline',
    record_hash                 VARCHAR(64) NOT NULL COMMENT 'SHA-256 over the row''s business columns. Stable across reruns with the same seed - this is what the determinism test compares.',
    CONSTRAINT pk_fct_membertransactions PRIMARY KEY (transaction_id)
)
COMMENT = 'One row per claim line, payment, adjustment or reversal | Financial and utilisation transaction history. Claim lines carry the diagnosis and procedure detail that silver mines for conservative-care, imaging-prerequisite and step-therapy evidence. related_auth_number links post-service claims back to the authorization that permitted them.';

CREATE OR REPLACE TABLE M360MART.BRONZE.fct_memberEvents (
    event_id             VARCHAR(40) NOT NULL COMMENT 'Unique event identifier',
    member_id            VARCHAR(20) NOT NULL COMMENT 'Member',
    event_datetime_utc   TIMESTAMP_NTZ NOT NULL COMMENT 'When the event occurred',
    event_category       VARCHAR(30) NOT NULL COMMENT 'Kind of interaction',
    event_subtype        VARCHAR(60) COMMENT 'Finer classification',
    channel              VARCHAR(30) NOT NULL COMMENT 'Channel used (PHONE, PORTAL, MAIL, FAX, SMS, EMAIL)',
    direction            VARCHAR(12) NOT NULL COMMENT 'INBOUND or OUTBOUND',
    related_pa_id        VARCHAR(24) COMMENT 'PA case this interaction concerns',
    related_claim_id     VARCHAR(40) COMMENT 'Claim this interaction concerns',
    handled_by_queue     VARCHAR(60) COMMENT 'Servicing queue',
    agent_id             VARCHAR(40) COMMENT 'Handling agent identifier',
    duration_seconds     NUMBER(8,0) COMMENT 'Interaction duration for voice contacts',
    disposition_code     VARCHAR(20) COMMENT 'Outcome code',
    disposition_desc     VARCHAR(300) COMMENT 'Outcome description',
    topic                VARCHAR(80) COMMENT 'What the contact was about',
    resolved_flag        BOOLEAN NOT NULL COMMENT 'True when resolved on this contact',
    escalated_flag       BOOLEAN NOT NULL COMMENT 'True when escalated',
    sentiment_score      NUMBER(4,3) COMMENT 'Synthetic sentiment between -1 and 1',
    notes_text           VARCHAR(2000) COMMENT 'Short interaction note',
    source_system        VARCHAR(40) NOT NULL COMMENT 'Originating system for this row (SYNTHEA, CMS_SYNPUF, FDA_NDC, CMS_ICD10, CMS_HCPCS, NPPES, SYNTHETIC, DERIVED)',
    ingested_at_utc      TIMESTAMP_NTZ NOT NULL COMMENT 'UTC timestamp the row was produced by the local pipeline',
    record_hash          VARCHAR(64) NOT NULL COMMENT 'SHA-256 over the row''s business columns. Stable across reruns with the same seed - this is what the determinism test compares.',
    CONSTRAINT pk_fct_memberevents PRIMARY KEY (event_id)
)
COMMENT = 'One row per member interaction or communication event | Member-facing contact history across all channels. related_pa_id ties correspondence to the PA case it concerns, which is how an analyst sees whether a pend letter actually went out and whether the member or provider responded.';

CREATE OR REPLACE TABLE M360MART.BRONZE.ext_patientProfile (
    ext_patient_id                  VARCHAR(40) NOT NULL COMMENT 'Provider medical record number (MRN-#######)',
    source_org_id                   VARCHAR(30) NOT NULL COMMENT 'Contributing provider organization identifier',
    source_org_name                 VARCHAR(300) NOT NULL COMMENT 'Contributing provider organization name',
    source_ehr_vendor               VARCHAR(40) NOT NULL COMMENT 'EHR platform the data came from',
    data_sharing_agreement_id       VARCHAR(40) NOT NULL COMMENT 'Governing data-sharing agreement',
    vbc_contract_id                 VARCHAR(40) COMMENT 'Value-based-care contract, when attributed',
    payer_member_id                 VARCHAR(20) COMMENT 'Payer member id as asserted by the provider. NULL or wrong on a realistic minority of rows - this is what forces identity resolution.',
    payer_member_id_asserted_flag   BOOLEAN NOT NULL COMMENT 'True when the provider supplied a member id at all',
    match_method                    VARCHAR(20) COMMENT 'How the record was matched to a member',
    match_confidence_score          NUMBER(5,4) COMMENT 'Match confidence between 0 and 1',
    first_name                      VARCHAR(100) COMMENT 'Given name as recorded by the provider',
    last_name                       VARCHAR(100) COMMENT 'Family name as recorded by the provider',
    date_of_birth                   DATE COMMENT 'Date of birth as recorded by the provider',
    gender                          VARCHAR(2) COMMENT 'Gender as recorded by the provider',
    address_line1                   VARCHAR(200) COMMENT 'Street address. Excluded from SERVING views.',
    city                            VARCHAR(100) COMMENT 'City',
    state                           VARCHAR(2) COMMENT 'State',
    zip_code                        VARCHAR(10) COMMENT 'Postal code',
    phone                           VARCHAR(30) COMMENT 'Phone. Excluded from SERVING views.',
    primary_care_provider_npi       VARCHAR(10) COMMENT 'Treating PCP NPI',
    primary_care_provider_name      VARCHAR(300) COMMENT 'Treating PCP name',
    attributed_flag                 BOOLEAN NOT NULL COMMENT 'True when attributed to the VBC contract',
    attribution_start_date          DATE COMMENT 'Attribution period start',
    attribution_end_date            DATE COMMENT 'Attribution period end',
    risk_score_hcc                  NUMBER(6,3) COMMENT 'HCC risk score',
    risk_tier                       VARCHAR(20) COMMENT 'LOW, MODERATE, HIGH or VERY_HIGH',
    last_encounter_date             DATE COMMENT 'Most recent encounter at this organization',
    consent_on_file_flag            BOOLEAN NOT NULL COMMENT 'True when patient consent to share is recorded',
    consent_scope                   VARCHAR(60) COMMENT 'Scope of the recorded consent',
    source_system                   VARCHAR(40) NOT NULL COMMENT 'Originating system for this row (SYNTHEA, CMS_SYNPUF, FDA_NDC, CMS_ICD10, CMS_HCPCS, NPPES, SYNTHETIC, DERIVED)',
    ingested_at_utc                 TIMESTAMP_NTZ NOT NULL COMMENT 'UTC timestamp the row was produced by the local pipeline',
    record_hash                     VARCHAR(64) NOT NULL COMMENT 'SHA-256 over the row''s business columns. Stable across reruns with the same seed - this is what the determinism test compares.',
    CONSTRAINT pk_ext_patientprofile PRIMARY KEY (ext_patient_id)
)
COMMENT = 'One row per patient per contributing provider organization | Provider-side patient identity under a VBC data-sharing agreement. The same human may appear here and in dim_memberProfile under different identifiers; payer_member_id is absent or conflicting for a realistic minority of rows.';

CREATE OR REPLACE TABLE M360MART.BRONZE.ext_patientClinicalRecords (
    clinical_record_id        VARCHAR(40) NOT NULL COMMENT 'Unique clinical record identifier',
    ext_patient_id            VARCHAR(40) NOT NULL COMMENT 'Provider patient identifier',
    payer_member_id           VARCHAR(20) COMMENT 'Payer member id when resolvable',
    source_org_id             VARCHAR(30) NOT NULL COMMENT 'Contributing organization',
    record_type               VARCHAR(30) NOT NULL COMMENT 'Kind of clinical record',
    record_date               DATE NOT NULL COMMENT 'Clinical date of the record',
    recorded_datetime_utc     TIMESTAMP_NTZ COMMENT 'When it was charted',
    encounter_ref             VARCHAR(64) COMMENT 'Encounter this record belongs to',
    source_code               VARCHAR(30) COMMENT 'Native code as recorded in the EHR',
    source_code_system        VARCHAR(12) COMMENT 'Native code system',
    source_code_desc          VARCHAR(500) COMMENT 'Native code description',
    icd10_code                VARCHAR(10) COMMENT 'Crosswalked ICD-10-CM diagnosis code',
    icd10_desc                VARCHAR(500) COMMENT 'Crosswalked ICD-10-CM description',
    cpt_hcpcs_code            VARCHAR(10) COMMENT 'Crosswalked CPT/HCPCS procedure code',
    cpt_hcpcs_desc            VARCHAR(500) COMMENT 'Crosswalked CPT/HCPCS description',
    crosswalk_method          VARCHAR(30) COMMENT 'How the crosswalk was derived (CURATED_MAP, CATEGORY_DEFAULT, UNMAPPED)',
    clinical_status           VARCHAR(20) COMMENT 'ACTIVE, RESOLVED or REMISSION',
    onset_date                DATE COMMENT 'Onset date for conditions',
    resolved_date             DATE COMMENT 'Resolution date for conditions',
    is_chronic_flag           BOOLEAN NOT NULL COMMENT 'True for chronic conditions',
    result_value_numeric      NUMBER(18,6) COMMENT 'Numeric result for labs and vitals',
    result_value_text         VARCHAR(500) COMMENT 'Text result when not numeric',
    result_unit               VARCHAR(40) COMMENT 'Unit of measure',
    reference_range_low       NUMBER(18,6) COMMENT 'Lower bound of the normal range',
    reference_range_high      NUMBER(18,6) COMMENT 'Upper bound of the normal range',
    abnormal_flag             VARCHAR(10) COMMENT 'NORMAL, HIGH, LOW or CRITICAL',
    body_site                 VARCHAR(120) COMMENT 'Anatomical site',
    body_region               VARCHAR(60) COMMENT 'Coarse body region - used to match imaging prerequisites and conservative care to the request',
    laterality                VARCHAR(20) COMMENT 'LEFT, RIGHT, BILATERAL or NA',
    severity                  VARCHAR(20) COMMENT 'MILD, MODERATE or SEVERE',
    performing_provider_npi   VARCHAR(10) COMMENT 'Provider who performed or recorded it',
    source_system             VARCHAR(40) NOT NULL COMMENT 'Originating system for this row (SYNTHEA, CMS_SYNPUF, FDA_NDC, CMS_ICD10, CMS_HCPCS, NPPES, SYNTHETIC, DERIVED)',
    ingested_at_utc           TIMESTAMP_NTZ NOT NULL COMMENT 'UTC timestamp the row was produced by the local pipeline',
    record_hash               VARCHAR(64) NOT NULL COMMENT 'SHA-256 over the row''s business columns. Stable across reruns with the same seed - this is what the determinism test compares.',
    CONSTRAINT pk_ext_patientclinicalrecords PRIMARY KEY (clinical_record_id)
)
COMMENT = 'One row per discrete clinical record (a diagnosis, procedure, lab, vital or imaging result) | Clinical detail from provider EHRs. Source codes are the native SNOMED-CT / LOINC values; the icd10_* and cpt_hcpcs_* columns are the crosswalked equivalents, because PA is transacted on ICD-10 and CPT/HCPCS and an analyst works in those code sets, not SNOMED.';

CREATE OR REPLACE TABLE M360MART.BRONZE.ext_patientEhrEvents (
    ehr_event_id              VARCHAR(40) NOT NULL COMMENT 'Unique event identifier',
    ext_patient_id            VARCHAR(40) NOT NULL COMMENT 'Provider patient identifier',
    payer_member_id           VARCHAR(20) COMMENT 'Payer member id when resolvable',
    source_org_id             VARCHAR(30) NOT NULL COMMENT 'Contributing organization',
    source_ehr_vendor         VARCHAR(40) NOT NULL COMMENT 'EHR platform',
    event_datetime_utc        TIMESTAMP_NTZ NOT NULL COMMENT 'When the event occurred clinically',
    received_datetime_utc     TIMESTAMP_NTZ NOT NULL COMMENT 'When the payer received the message',
    ingestion_latency_hours   NUMBER(8,2) NOT NULL COMMENT 'Hours between occurrence and receipt',
    event_type                VARCHAR(30) NOT NULL COMMENT 'Kind of event',
    adt_message_type          VARCHAR(10) COMMENT 'HL7 ADT message type (A01, A03, A04, A08)',
    encounter_id              VARCHAR(64) COMMENT 'Encounter identifier',
    encounter_class           VARCHAR(20) COMMENT 'Encounter setting',
    encounter_reason_code     VARCHAR(30) COMMENT 'Reason code for the encounter',
    encounter_reason_desc     VARCHAR(500) COMMENT 'Reason description',
    department                VARCHAR(120) COMMENT 'Department or unit',
    location                  VARCHAR(200) COMMENT 'Facility or location name',
    attending_provider_npi    VARCHAR(10) COMMENT 'Attending provider NPI',
    admission_datetime_utc    TIMESTAMP_NTZ COMMENT 'Admission timestamp for inpatient events',
    discharge_datetime_utc    TIMESTAMP_NTZ COMMENT 'Discharge timestamp',
    length_of_stay_days       NUMBER(8,2) COMMENT 'Length of stay in days',
    discharge_disposition     VARCHAR(120) COMMENT 'Where the patient went at discharge',
    order_type                VARCHAR(60) COMMENT 'Order category for order events',
    order_code                VARCHAR(30) COMMENT 'Ordered item code',
    order_desc                VARCHAR(500) COMMENT 'Ordered item description',
    order_status              VARCHAR(30) COMMENT 'PLACED, IN_PROGRESS, COMPLETED or CANCELLED',
    referral_specialty        VARCHAR(150) COMMENT 'Specialty referred to',
    referral_reason           VARCHAR(500) COMMENT 'Reason for referral',
    source_system             VARCHAR(40) NOT NULL COMMENT 'Originating system for this row (SYNTHEA, CMS_SYNPUF, FDA_NDC, CMS_ICD10, CMS_HCPCS, NPPES, SYNTHETIC, DERIVED)',
    ingested_at_utc           TIMESTAMP_NTZ NOT NULL COMMENT 'UTC timestamp the row was produced by the local pipeline',
    record_hash               VARCHAR(64) NOT NULL COMMENT 'SHA-256 over the row''s business columns. Stable across reruns with the same seed - this is what the determinism test compares.',
    CONSTRAINT pk_ext_patientehrevents PRIMARY KEY (ehr_event_id)
)
COMMENT = 'One row per EHR event message | Near-real-time event stream from partner EHRs, modelled on ADT and order messaging. ingestion_latency_hours preserves the fact that these feeds lag, which matters when an analyst asks whether an admission has actually been reported yet.';

CREATE OR REPLACE TABLE M360MART.BRONZE.ext_patientMedicalHistory (
    medical_history_id        VARCHAR(40) NOT NULL COMMENT 'Unique history record identifier',
    ext_patient_id            VARCHAR(40) NOT NULL COMMENT 'Provider patient identifier',
    payer_member_id           VARCHAR(20) COMMENT 'Payer member id when resolvable',
    source_org_id             VARCHAR(30) NOT NULL COMMENT 'Contributing organization',
    history_type              VARCHAR(30) NOT NULL COMMENT 'Kind of history entry',
    onset_date                DATE COMMENT 'Start date',
    end_date                  DATE COMMENT 'End date, NULL when ongoing',
    is_active                 BOOLEAN NOT NULL COMMENT 'True when currently active',
    condition_snomed_code     VARCHAR(30) COMMENT 'SNOMED-CT condition code',
    condition_icd10_code      VARCHAR(10) COMMENT 'Crosswalked ICD-10-CM condition code',
    condition_desc            VARCHAR(500) COMMENT 'Condition description',
    condition_category        VARCHAR(60) COMMENT 'Coarse condition grouping',
    medication_rxnorm_code    VARCHAR(30) COMMENT 'RxNorm concept code',
    medication_ndc_code       VARCHAR(20) COMMENT 'NDC product code',
    medication_name           VARCHAR(300) COMMENT 'Medication as prescribed',
    medication_generic_name   VARCHAR(300) COMMENT 'Generic name',
    therapeutic_class         VARCHAR(120) COMMENT 'Therapeutic class - step therapy is evaluated within a class',
    dose_amount               VARCHAR(60) COMMENT 'Dose amount',
    dose_unit                 VARCHAR(40) COMMENT 'Dose unit',
    route                     VARCHAR(60) COMMENT 'Route of administration',
    frequency                 VARCHAR(60) COMMENT 'Dosing frequency',
    sig_text                  VARCHAR(500) COMMENT 'Prescription directions',
    prescriber_npi            VARCHAR(10) COMMENT 'Prescribing provider NPI',
    prescribed_date           DATE COMMENT 'Date prescribed',
    discontinued_date         DATE COMMENT 'Date discontinued',
    discontinue_reason        VARCHAR(200) COMMENT 'Why it was stopped - ''inadequate response'' is what satisfies a fail-first criterion',
    dispense_count            NUMBER(6,0) COMMENT 'Number of dispenses',
    days_supply_total         NUMBER(8,0) COMMENT 'Cumulative days supply',
    therapy_duration_days     NUMBER(8,0) COMMENT 'Days between first and last dispense - measures trial duration',
    adherence_pdc_pct         NUMBER(5,2) COMMENT 'Proportion of days covered - distinguishes a genuine failed trial from non-adherence',
    is_specialty_drug         BOOLEAN COMMENT 'True for specialty/biologic products',
    requires_pa_flag          BOOLEAN COMMENT 'True when the drug is PA-gated',
    formulary_tier            NUMBER(2,0) COMMENT 'Formulary tier',
    is_first_line_therapy     BOOLEAN COMMENT 'True when this drug is a first-line option in its class',
    allergy_substance         VARCHAR(300) COMMENT 'Allergen',
    allergy_reaction          VARCHAR(300) COMMENT 'Observed reaction',
    allergy_severity          VARCHAR(20) COMMENT 'MILD, MODERATE or SEVERE',
    allergy_criticality       VARCHAR(20) COMMENT 'LOW, HIGH or UNABLE_TO_ASSESS',
    immunization_cvx_code     VARCHAR(10) COMMENT 'CVX vaccine code',
    immunization_desc         VARCHAR(300) COMMENT 'Vaccine description',
    smoking_status            VARCHAR(40) COMMENT 'Smoking status',
    bmi_value                 NUMBER(6,2) COMMENT 'Body mass index - the threshold input for bariatric criteria',
    bmi_recorded_date         DATE COMMENT 'Date the BMI was recorded',
    height_cm                 NUMBER(6,2) COMMENT 'Height in centimetres',
    weight_kg                 NUMBER(7,2) COMMENT 'Weight in kilograms',
    notes_text                VARCHAR(1000) COMMENT 'Free-text note',
    source_system             VARCHAR(40) NOT NULL COMMENT 'Originating system for this row (SYNTHEA, CMS_SYNPUF, FDA_NDC, CMS_ICD10, CMS_HCPCS, NPPES, SYNTHETIC, DERIVED)',
    ingested_at_utc           TIMESTAMP_NTZ NOT NULL COMMENT 'UTC timestamp the row was produced by the local pipeline',
    record_hash               VARCHAR(64) NOT NULL COMMENT 'SHA-256 over the row''s business columns. Stable across reruns with the same seed - this is what the determinism test compares.',
    CONSTRAINT pk_ext_patientmedicalhistory PRIMARY KEY (medical_history_id)
)
COMMENT = 'One row per longitudinal history item (a condition, medication, allergy, immunization or history entry) | Longitudinal patient history. The medication rows carry trial dates and PDC adherence, which is exactly what a step-therapy criterion needs; bmi_value supports the bariatric BMI thresholds. This is the primary evidence source for medical-necessity criteria evaluation.';
