-- M360MART RBAC
-- M360_APP_ROLE: USAGE on database + SERVING only, SELECT on views only
-- M360_ENGINEER_ROLE: full access to all schemas

-- Roles
CREATE ROLE IF NOT EXISTS M360_APP_ROLE;
CREATE ROLE IF NOT EXISTS M360_ENGINEER_ROLE;

-- Engineer role: full access
GRANT USAGE ON DATABASE M360MART TO ROLE M360_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA M360MART.BRONZE TO ROLE M360_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA M360MART.SILVER TO ROLE M360_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA M360MART.GOLD TO ROLE M360_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA M360MART.SERVING TO ROLE M360_ENGINEER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA M360MART.BRONZE TO ROLE M360_ENGINEER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA M360MART.SILVER TO ROLE M360_ENGINEER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA M360MART.GOLD TO ROLE M360_ENGINEER_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA M360MART.SERVING TO ROLE M360_ENGINEER_ROLE;

-- App role: SERVING only
GRANT USAGE ON DATABASE M360MART TO ROLE M360_APP_ROLE;
GRANT USAGE ON SCHEMA M360MART.SERVING TO ROLE M360_APP_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA M360MART.SERVING TO ROLE M360_APP_ROLE;

-- Explicitly NO grants on BRONZE/SILVER/GOLD for app role
-- (verified by the end-to-end RBAC negative test)

-- Warehouse access
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE M360_APP_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE M360_ENGINEER_ROLE;
