-- RBAC for the PA copilot app layer.
--
-- Extends M360_APP_ROLE to the new SERVING objects ONLY. The existing negative
-- guarantee must continue to hold: the app role can see nothing in BRONZE, SILVER or
-- GOLD. validate/validate_app.py asserts that as a test, not as an assumption.

USE ROLE ACCOUNTADMIN;

-- Corpus tables the copilot reads for citations
GRANT SELECT ON TABLE M360MART.SERVING.REGULATORY_CHUNKS TO ROLE M360_APP_ROLE;
GRANT SELECT ON TABLE M360MART.SERVING.REGULATORY_SOURCES TO ROLE M360_APP_ROLE;
GRANT SELECT ON TABLE M360MART.SERVING.RADIOLOGY_REFERENCE TO ROLE M360_APP_ROLE;

-- READ, not WRITE: the app renders these documents and images, it never modifies
-- them. Write access would let a compromised app session alter the very sources its
-- citations point at.
GRANT READ ON STAGE M360MART.SERVING.STG_REGULATORY TO ROLE M360_APP_ROLE;
GRANT READ ON STAGE M360MART.SERVING.STG_RADIOLOGY TO ROLE M360_APP_ROLE;

-- Retrieval and NL-to-SQL surfaces
GRANT USAGE ON CORTEX SEARCH SERVICE M360MART.SERVING.SVC_REGULATORY TO ROLE M360_APP_ROLE;
GRANT SELECT ON SEMANTIC VIEW M360MART.SERVING.SV_PA_COPILOT TO ROLE M360_APP_ROLE;

-- Cortex AI functions (AI_COMPLETE for summarisation, Cortex Analyst for NL-to-SQL)
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE M360_APP_ROLE;

-- Engineers keep full access for rebuilds
GRANT SELECT ON ALL TABLES IN SCHEMA M360MART.SERVING TO ROLE M360_ENGINEER_ROLE;
GRANT READ, WRITE ON STAGE M360MART.SERVING.STG_REGULATORY TO ROLE M360_ENGINEER_ROLE;
GRANT READ, WRITE ON STAGE M360MART.SERVING.STG_RADIOLOGY TO ROLE M360_ENGINEER_ROLE;
